from .learning_development_plot import learning_development_plot
from .Prediction_plot import Prediction_plot
from .QQ_plot import QQ_plot
from .Confusion_Matrix_Regression import Confusion_Matrix_Regression